# Generated by Django 3.0.6 on 2020-07-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinus',
            name='area',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='joinus',
            name='city',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='joinus',
            name='email',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='joinus',
            name='insta',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='joinus',
            name='name',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='joinus',
            name='phone',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='joinus',
            name='pincode',
            field=models.TextField(),
        ),
    ]
