# Generated by Django 3.0.6 on 2020-07-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200706_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinus',
            name='phone',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='joinus',
            name='pincode',
            field=models.TextField(max_length=6),
        ),
    ]
