# Generated by Django 3.0.6 on 2020-07-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200706_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinus',
            name='feedback',
        ),
    ]
