# Generated by Django 3.0.8 on 2020-07-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='Your Name', max_length=60),
        ),
    ]
