# Generated by Django 3.0.8 on 2020-07-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Name', max_length=60)),
                ('text', models.CharField(max_length=300)),
                ('subject', models.CharField(max_length=80)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
