# Generated by Django 3.0.8 on 2020-07-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='ContactUs',
        ),
    ]
