# Generated by Django 3.0.8 on 2020-07-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinUs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinus',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='joinus',
            name='pincode',
            field=models.PositiveIntegerField(),
        ),
    ]
